fix tf acceptance tests
Тесты регулярно [падали](https://teamcity.aw.cloud.yandex.net/buildConfiguration/PublicAPI_Terraform_AcceptanceTests_Kubernetes_Combo/23167103?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) с

```
------- Stdout: -------
=== RUN   TestAccKubernetesNodeGroup_networkSettings
    resource_yandex_kubernetes_node_group_test.go:469: Step 3/3 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.
          map[string]string{
        -   "status": "running",
        +   "status": "reconciling",
          }
--- FAIL: TestAccKubernetesNodeGroup_networkSettings (771.32s)
```

Также иногда воспроизводится локально на дев кластере: операция завершилась, но нод группа в статусе RECONCILING

```shell
% ycplp k8s node-group update -r /Users/$USER/.config/mk8sdev/prod/examples/node_group_update.yaml
done (4s)
id: tttvnu2v7o44ucc8hje1
cluster_id: tttvu6hbq534osk98cfj
created_at: "2025-08-28T12:04:04Z"
status: RUNNING
...

% ycplp k8s node-group get tttvnu2v7o44ucc8hje1
id: tttvnu2v7o44ucc8hje1
cluster_id: tttvu6hbq534osk98cfj
created_at: "2025-08-28T12:04:04Z"
status: RECONCILING
...
```

Поэтому добавляю статус в игнорируемые поля
commit_hash:130876410ca8b909458d592368ab8e6ba56b5f94